import {
  Presentation,
  BarChart3,
  Map as MapIcon,
  Network,
  Palette
} from 'lucide-react';

export const CATEGORIES = {
  PRESENTATION: {
    id: 'presentation',
    label: 'Prezentáció és Diák',
    icon: <Presentation className="w-4 h-4" />,
    templates: [
      { id: 'p1', name: '5 diás előadásvázlat', task: 'Készítsen képet egy 5 diás előadásvázlatról a(z) [TOPIC] témában, biztosítva a logikus előrehaladást az "Előzetes tudás" szintjétől a "Haladó alkalmazásig".', style: 'Structured Academic Presentation', composition: 'Clean slide layouts, balanced text-to-visual ratio', elements: 'Progress indicators, section headers, focus points', palette: 'Professional blue and grey', lighting: 'Soft studio lighting', goal: 'Strukturált ismeretátadás.' },
      { id: 'p2', name: 'Nagy kép metafora', task: 'Készítsen képet egy "Nagy kép" dia leírásáról, amely egy központi metaforát használ a(z) [TOPIC] elmagyarázására.', style: 'Conceptual Metaphor Illustration', composition: 'Single dominant central icon with surrounding nodes', elements: 'Visual analogy, symbolic objects, simplified labels', palette: 'High-contrast symbolic colors', lighting: 'Dramatic focal light', goal: 'Kognitív horgony kialakítása.' },
      { id: 'p3', name: 'Tévhit – Korrekció', task: 'Készítsen képet egy "Gyakori tévhitek" diáról, amely három mítoszt és azok bizonyítékokon alapuló korrekcióit sorolja fel a(z) [TOPIC] témában.', style: 'Informational Educational Graphic', composition: 'Split screen: Myth vs. Reality', elements: 'Alert icons, checkmarks, evidence bubbles', palette: 'Red and green accents on white', lighting: 'Clarity-focused studio lighting', goal: 'Kritikai gondolkodás fejlesztése.' },
      { id: 'p4', name: 'Hármas szabály (Key Takeaways)', task: 'Készítsen képet egy összefoglaló diáról a(z) [TOPIC] témában a "hármas szabály" alkalmazásával: 3 fő pont, mindegyikhez 1–1 támogató részrettel.', style: 'Minimalist Summary Slide', composition: 'Three vertical columns or blocks', elements: 'Clear numbering, focus icons, concise text', palette: 'Neutral with one accent color', lighting: 'Even flat lighting', goal: 'Lényeglátás segítése.' },
      { id: 'p5', name: 'Probléma–Megoldás–Hatás', task: 'Készítsen képet egy Probléma–Megoldás–Hatás dia elrendezésről a(z) [TOPIC] számára.', style: 'Strategic Narrative Slide', composition: 'Three-stage horizontal progression', elements: 'Problem icon, solution gears, impact spark', palette: 'Gradient from cool to warm tones', lighting: 'Directional stage lighting', goal: 'Folyamat és eredmény láttatása.' },
      { id: 'p6', name: 'Flash Talk script', task: 'Készítsen képet egy 60 másodperces villámelőadás forgatókönyvéről, amely csak a(z) [TOPIC] legkritikusabb aspektusára fókuszál.', style: 'Dynamic Script Layout', composition: 'Timed segments with visual cues', elements: 'Hook, main argument, call to action', palette: 'High energy colors', lighting: 'Spotlight focus', goal: 'Hatékony kommunikáció.' },
      { id: 'p7', name: 'Vizuális szókincs', task: 'Készítsen képet egy vizuális szókincs diáról: soroljon fel 5 kulcsfogalmat a(z) [TOPIC] témában, és rendeljen mindegyikhez egy egyszerű ikont.', style: 'Iconographic Dictionary', composition: 'Grid of 5 circular nodes', elements: 'Simple vector icons, bold labels', palette: 'Distinctive categorical colors', lighting: 'Shadowless flat design', goal: 'Fogalmi rögzítés.' },
      { id: 'p8', name: 'Híd–dia (Átvezetés)', task: 'Készítsen képet egy híd–diáról, amely logikus átmenetet képez egy korábbi témáról a(z) [TOPIC] témára.', style: 'Relational Transition Graphic', composition: 'Two large areas connected by a central bridge', elements: 'Previous topic anchor, [TOPIC] focus, logic arrows', palette: 'Analogous colors', lighting: 'Connecting glow effect', goal: 'Asszociációs háló építése.' },
      { id: 'p9', name: 'Lépésről lépésre folyamat', task: 'Készítsen képet egy folyamatlebontásról a(z) [TOPIC] számára, pontosan 5 világos és cselekvésközpontú szakaszra osztva.', style: 'Step-by-Step Educational Path', composition: 'Numbered sequence track', elements: 'Numbered badges, action verbs, small illustrations', palette: 'Sequential blue shades', lighting: 'Top-down clarity', goal: 'Procedurális tudás.' },
      { id: 'p10', name: 'Összehasonlító táblázat', task: 'Készítsen képet egy összehasonlító táblázatról a(z) [TOPIC] különböző aspektusaihoz négy konkrét változó mentén.', style: 'Technical Comparison Matrix', composition: 'Grid-based structured layout', elements: 'Checkmarks, variable labels, differentiation icons', palette: 'Muted neutral tones', lighting: 'Even flat lighting', goal: 'Differenciált szemléletmód.' }
    ]
  },
  INFOGRAPHICS: {
    id: 'infographics',
    label: 'Infografika és Adat',
    icon: <BarChart3 className="w-4 h-4" />,
    templates: [
      { id: 'i1', name: 'Anatómia vizualizáció', task: 'Készítsen képet egy "A(z) [TOPIC] anatómiája" típusú infografikáról, amely alkotórészeire bontja a fogalmat/tárgyat.', style: 'Exploded View Technical Illustration', composition: 'Central object with radial callouts', elements: 'Leader lines, detailed textures, component labels', palette: 'Naturalistic or technical colors', lighting: 'Ambient occlusion, detailed shadows', goal: 'Szerkezeti elemzés.' },
      { id: 'i2', name: 'Fejlődési idővonal', task: 'Készítsen képet egy "Fejlődési idővonalról" a(z) [TOPIC] témához, kiemelve az 5 legfontosabb fordulópontot.', style: 'Clean Linear Timeline', composition: 'Horizontal or zig-zag path', elements: 'Chronological markers, event icons, short descriptions', palette: 'Sequential color gradient', lighting: 'Even daylight', goal: 'Történeti kontextus megértése.' },
      { id: 'i3', name: 'Hatásfolyamat ábra', task: 'Készítsen képet egy "Hatásfolyamat" ábráról, amely bemutatja, hogyan befolyásolja a(z) [TOPIC] a rendszerszintű eredményeket.', style: 'Flowchart with depth', composition: 'Cause-to-effect directional flow', elements: 'Impact nodes, weighted arrows, feedback loops', palette: 'Professional corporate palette', lighting: 'Top-down diffused lighting', goal: 'Okozati összefüggések feltárása.' },
      { id: 'i4', name: 'Számok tükrében', task: 'Készítsen képet egy "A számok tükrében" típusú infografikáról, amely a(z) [TOPIC] statisztikai jelentőségére fókuszál.', style: 'Data-Driven Dashboard', composition: 'Collection of distinct metric cards', elements: 'Pie charts, bar graphs, large hero numbers', palette: 'Monochromatic with high-contrast text', lighting: 'Crisp digital display', goal: 'Kvantitatív összefüggések.' },
      { id: 'i5', name: 'Érvek és Ellenérvek', task: 'Készítsen képet egy vizuális mérlegről az érvek és ellenérvek bemutatására a(z) [TOPIC] kapcsán.', style: 'Balanced Comparison Sheet', composition: 'Symmetrical split layout', elements: 'Weights, scale icons, contrasting bullet points', palette: 'Cool blue vs warm amber', lighting: 'Neutral studio light', goal: 'Objektív elemzés.' },
      { id: 'i6', name: 'Fontossági hierarchia', task: 'Készítsen képet egy fontossági hierarchia listáról a(z) [TOPIC] számára egy piramis struktúra használatával.', style: 'Hierarchical Pyramid Structure', composition: 'Triangular layered sections', elements: 'Foundational blocks, peak achievement, layer labels', palette: 'Gradated saturation from bottom up', lighting: 'Uplighting effect', goal: 'Strukturális prioritások.' },
      { id: 'i7', name: 'Globális vs. Lokális', task: 'Készítsen képet egy összehasonlító elrendezésről, amely bemutatja a(z) [TOPIC] hatásait globális és lokális léptékben.', style: 'Multi-scale Spatial Comparison', composition: 'Macro-view globe beside Micro-view map', elements: 'Scale markers, localized icons, global trends', palette: 'Earth tones', lighting: 'Dual-source illumination', goal: 'Léptékváltó gondolkodás.' },
      { id: 'i8', name: 'Siker–ellenőrzőlista', task: 'Készítsen képet egy "Út a sikerhez" infografika ellenőrzőlistáról a(z) [TOPIC] elsajátításához.', style: 'Gamified Checklist Graphic', composition: 'Winding path with checkboxes', elements: 'Milestone flags, progress bar, success trophy', palette: 'Vibrant achievement colors', lighting: 'Bright optimistic lighting', goal: 'Tanulási útmutatás.' },
      { id: 'i9', name: 'Folyamatciklusa', task: 'Készítsen képet egy folyamatciklus leírásról, biztosítva, hogy a(z) [TOPIC] utolsó és első fázisa közötti hurok világosan látható legyen.', style: 'Circular Iterative Model', composition: 'Closed loop ring', elements: 'Recycling arrows, continuous flow nodes', palette: 'Harmonious circular palette', lighting: 'Even internal glow', goal: 'Ciklikus folyamatok megértése.' },
      { id: 'i10', name: 'Puska–módszer (Cheat Sheet)', task: 'Készítsen képet egy Cheat Sheet elrendezésről, amely komplex információkat sűrít egyetlen vizuális útmutatóba a(z) [TOPIC] kapcsán.', style: 'Condensed Information Density', composition: 'Multimodal grid (text, icon, chart)', elements: 'Quick-reference boxes, mnemonic icons', palette: 'High-readability contrast', lighting: 'Office/Desk lighting clarity', goal: 'Hatékony összegzés.' }
    ]
  },
  SPATIAL: {
    id: 'spatial',
    label: 'Térbeli és Kapcsolati',
    icon: <MapIcon className="w-4 h-4" />,
    templates: [
      { id: 's1', name: 'Tudástérkép', task: 'Készítsen képet egy "Tudástérkép" leírásról, amely bemutatja a(z) [TOPIC] interdiszciplináris kapcsolatait.', style: 'Cartographic Knowledge Map', composition: 'Island or network cluster view', elements: 'Bridge icons, terrain of concepts, connection lines', palette: 'Vintage map aesthetic', lighting: 'Warm parchment glow', goal: 'Rendszerszemléletű integráció.' },
      { id: 's2', name: 'Venn-diagram', task: 'Készítsen képet egy Venn-diagram leírásáról, azonosítva a(z) [TOPIC] egyedi és közös vonásait más releváns fogalmakkal.', style: 'Minimalist Overlap Diagram', composition: 'Intersecting circles with clear central labels', elements: 'Shaded intersection, distinct node icons', palette: 'Translucent primary colors', lighting: 'Flat graphic lighting', goal: 'Hasonlóságok és különbségek elemzése.' },
      { id: 's3', name: 'Hálózati diagram', task: 'Készítsen képet egy hálózati diagramról, amely bemutatja az 5 legfontosabb érintett közötti kapcsolatot a(z) [TOPIC] területén.', style: 'Social Network Graph', composition: 'Node-and-link constellation', elements: 'Stakeholder avatars, relational arrows, weight indicators', palette: 'Divergent categorical colors', lighting: 'Subtle neon glow for nodes', goal: 'Társadalmi/rendszeri dinamika.' },
      { id: 's4', name: 'Térbeli eloszlás', task: 'Készítsen képet egy térbeli eloszlás összefoglalóról: magyarázza el, hol a legjellemzőbb a(z) [TOPIC] és miért.', style: 'Heatmap Distribution View', composition: 'Geographic map with intensity gradients', elements: 'Density markers, regional labels, trend lines', palette: 'Color intensity scale (blue to red)', lighting: 'Geographic overlay lighting', goal: 'Térbeli mintázatok felismerése.' },
      { id: 's5', name: 'Mozgás és Áramlás', task: 'Készítsen képet egy "Mozgás és Áramlás" leírásról, amely bemutatja az információk áramlását a(z) [TOPIC] rendszerén binnen.', style: 'Kinetic Flow Diagram', composition: 'Dynamic directional streams', elements: 'Flow velocity arrows, bottleneck icons, source/sink nodes', palette: 'Fluid gradients', lighting: 'Motion blur effect', goal: 'Dinamikai elemzés.' },
      { id: 's6', name: 'Zónázott elemzés', task: 'Készítsen képet egy belső és külső tényezőkre osztott zónázott elemzésről a(z) [TOPIC] számára.', style: 'Concentric Zonal Layout', composition: 'Inside-out partitioned circles', elements: 'Internal core factors, external environmental influences', palette: 'Warm interior, cool exterior', lighting: 'Focal center light', goal: 'Környezeti analízis.' },
      { id: 's7', name: 'Koncentrikus körök', task: 'Készítsen képet egy koncentrikus körmodellről: helyezze a(z) [TOPIC] magját a középpontba, a kapcsolódó rétegeket pedig kívülre.', style: 'Onion-Skin Model', composition: 'Multiple nested rings', elements: 'Core essence, secondary attributes, tertiary links', palette: 'Monochromatic saturation layers', lighting: 'Layered transparency shadows', goal: 'Mélységi struktúra.' },
      { id: 's8', name: 'Előtte és Utána', task: 'Készítsen képet egy vizuális összehasonlításról, amely bemutatja a(z) [TOPIC] hatását egy esemény előtt és után.', style: 'Temporal Split Comparison', composition: 'Vertical or horizontal side-by-side', elements: 'Transformation markers, growth indicators', palette: 'Desaturated "Before", vibrant "After"', lighting: 'Time-of-day progression', goal: 'Változáskövetés.' },
      { id: 's9', name: 'Ránagyítás (Drill–Down)', task: 'Készítsen képet egy "Drill–Down" struktúráról: induljon a(z) [TOPIC] széles áttekintésétől, majd "zoomoljon" egy konkrét esettanulmányra.', style: 'Telescopic View Illustration', composition: 'Series of increasingly detailed panels', elements: 'Overview map, focused lens, microscopic details', palette: 'Contextual blues and greys', lighting: 'Focus-pull effect', goal: 'Általánostól az egyediig.' },
      { id: 's10', name: 'Szórásdiagram logika', task: 'Készítsen képet egy szórásdiagram logikai vázlatáról: írja le, mely változók korrelálnak a(z) [TOPIC] kapcsán.', style: 'Analytical Scatter Plot', composition: 'Coordinate axis with clustered data points', elements: 'X/Y axis labels, outlier callouts, trend line', palette: 'Scientific muted tones', lighting: 'Even digital grid light', goal: 'Statisztikai mintázatkeresés.' }
    ]
  },
  DIAGRAMS: {
    id: 'diagrams',
    label: 'Modellek és Diagramok',
    icon: <Network className="w-4 h-4" />,
    templates: [
      { id: 'd1', name: 'Input–Process–Output', task: 'Készítsen képet egy Input–Process–Output rendszerdiagramról a(z) [TOPIC] folyamatához.', style: 'System Engineering Diagram', composition: 'Linear three-stage block layout', elements: 'Data stream icons, gear symbols, output result', palette: 'Industrial blue and orange', lighting: 'Clean tech lighting', goal: 'Folyamatoptimalizálás megértése.' },
      { id: 'd2', name: 'Hagyma–modell', task: 'Készítsen képet egy "Hagyma–modellről" a(z) [TOPIC] komplexitásának és rétegeinek elmagyarázására.', style: 'Concentric Circle Model', composition: 'Layered spheres with a core center', elements: 'Cutaway view, layer labels, depth indicators', palette: 'Monochromatic shades of blue', lighting: 'Internal core glow', goal: 'Mélységi elemzés.' },
      { id: 'd3', name: 'SWOT Analízis', task: 'Készítsen képet egy SWOT analízisről (Erősségek, Gyengeségek, Lehetőségek, Veszélyek) a(z) [TOPIC] stratégiájához.', style: 'Quadrant Matrix Style', composition: 'Four-cell balanced grid', elements: 'SWOT icons, bulleted lists, header icons', palette: 'Standard SWOT color coding (Green, Red, Blue, Yellow)', lighting: 'Neutral flat lighting', goal: 'Stratégiai értékelés.' },
      { id: 'd4', name: 'Halszálka (Ishikawa)', task: 'Készítsen képet egy Halszálka diagram vázlatáról a(z) [TOPIC] gyökérokainak azonosítására.', style: 'Root Cause Analysis Framework', composition: 'Skeleton-style horizontal flow', elements: 'Problem head, category ribs (People, Process, etc.)', palette: 'Technical grey and steel', lighting: 'Precision studio lighting', goal: 'Problémamegoldó elemzés.' },
      { id: 'd5', name: 'Döntési fa', task: 'Készítsen képet egy döntési fáról a(z) [TOPIC] számára, hogy segítsd a tanulóknak navigálni egy választási helyzetben.', style: 'Algorithmic Flow Layout', composition: 'Branching tree structure', elements: 'Decision nodes, branch paths, outcomes', palette: 'Binary contrast colors', lighting: 'Pathway illumination', goal: 'Logikai döntéshozatal.' },
      { id: 'd6', name: 'Visszacsatolási hurok', task: 'Készítsen képet egy visszacsatolási hurok diagramról a(z) [TOPIC] témában: mutassa be a folyamatok egymásra hatását.', style: 'Self-Regulating System Model', composition: 'Interconnected cyclic nodes', elements: 'Positive/negative signs, reinforcement arrows', palette: 'System dynamics palette', lighting: 'Dynamic energy glow', goal: 'Rendszerdinamika megértése.' },
      { id: 'd7', name: 'Gondolattérkép (Mind Map)', task: 'Készítsen képet egy gondolattérkép vázáról a(z) [TOPIC] központi témájával és 4 fő ággal.', style: 'Organic Mind Map Style', composition: 'Radial branching structure', elements: 'Central trunk, sub-topic branches, keyword icons', palette: 'Multi-colored semantic branches', lighting: 'Soft ambient clarity', goal: 'Asszociatív rögzítés.' },
      { id: 'd8', name: 'Spektrum / Kontinuum', task: 'Készítsen képet egy spektrum vagy kontinuum vizualizációról a(z) [TOPIC] számára, szélsőséges nézőpontokkal.', style: 'Linear Scale Visualization', composition: 'Horizontal line with pointer nodes', elements: 'Extreme labels, midpoint balance, variation markers', palette: 'Gradient from cold to warm', lighting: 'Balanced even spread', goal: 'Árnyalt szemléletmód.' },
      { id: 'd9', name: 'Híd–modell (Fejlődés)', task: 'Készítsen képet egy "Híd–modellről": mutassa be az elmozdulást az "A" állapotból a "B" állapotba a(z) [TOPIC] kapcsán.', style: 'Developmental Transition Bridge', composition: 'Two cliffs connected by a modular bridge', elements: 'Start state, end state, required tools/steps', palette: 'Growth greens and browns', lighting: 'Future-focused morning sun', goal: 'Fejlődési folyamat tervezése.' },
      { id: 'd10', name: 'Mérleg vizualizáció', task: 'Készítsen képet egy mérleg vizualizációról: mely tényezők emelik fel vagy húzzák le a(z) [TOPIC] helyzetét.', style: 'Equilibrium Metaphor', composition: 'Classical balance scale', elements: 'Weight blocks, lifting balloons, central fulcrum', palette: 'Heavy greys vs light yellows', lighting: 'Gravity-focused lighting', goal: 'Tényező–elemzés.' }
    ]
  },
  CREATIVE: {
    id: 'creative',
    label: 'Kreatív Tananyagok',
    icon: <Palette className="w-4 h-4" />,
    templates: [
      { id: 'c1', name: 'Múzeumi tábla', task: 'Készítsen képet egy "Múzeumi tábláról": foglalja össze a(z) [TOPIC] lényegét nagyközönség számára.', style: 'Museum Exhibit Plaque', composition: 'Elegant typography-focused layout', elements: 'Artifact silhouette, timeline snippet, key fact box', palette: 'Museum grey and gold accents', lighting: 'High-end gallery spotlight', goal: 'Közérthető ismeretterjesztés.' },
      { id: 'c2', name: 'Esettanulmány pillanatkép', task: 'Készítsen képet egy "Esettanulmány pillanatképet" a(z) [TOPIC] témában.', style: 'Editorial Case Study Layout', composition: 'Vertical card style with sidebar', elements: 'Statistical graphs, quote marks, focus icon', palette: 'Academic journal aesthetic', lighting: 'Soft window light', goal: 'Gyakorlati alkalmazás.' },
      { id: 'c3', name: 'Vizuális metafora prompt', task: 'Készítsen képet egy vizuális metaforáról: "Ha a(z) [TOPIC] egy gép/organizmus/épület lenne, hogyan működne?".', style: 'Surreal Educational Metaphor', composition: 'Detailed biomechanical or architectural cutaway', elements: 'Internal mechanisms, organic structures, functional labels', palette: 'Rich detailed textures', lighting: 'Dramatic cinematic lighting', goal: 'Absztrakt fogalmak konkretizálása.' },
      { id: 'c4', name: 'Szituáció–alapú kártya', task: 'Készítsen képet egy "Szituáció–alapú" tanulókártyáról: probléma és megoldás a(z) [TOPIC] alapján.', style: 'Flashcard Minimalist Style', composition: 'Front/Back mirrored layout', elements: 'Challenge icon, solution key, mnemonic aid', palette: 'High-contrast black and white', lighting: 'Flat studio lighting', goal: 'Problémamegoldás gyakorlása.' },
      { id: 'c5', name: 'Terepkalauz bejegyzés', task: 'Készítsen képet egy "Terepkalauz" bejegyzésről a(z) [TOPIC] számára, bemutatva a típusokat és funkciókat.', style: 'Naturalist Field Guide Illustration', composition: 'Botanical/Scientific sketch layout', elements: 'Annotated drawings, scale reference, habitat icons', palette: 'Watercolor and ink wash', lighting: 'Natural diffused daylight', goal: 'Rendszertani tudás.' },
      { id: 'c6', name: 'Social Media Feed', task: 'Készítsen képet egy Social Media Feed összefoglalóról: magyarázza el a(z) [TOPIC] lényegét 5 tömör posztban.', style: 'Modern Social Media Feed', composition: 'Sequence of mobile-style card frames', elements: 'Profile avatars, engagement icons, hashtags', palette: 'UI-standard vibrant blues/greys', lighting: 'Smartphone screen glow', goal: 'Tartalomszintézis.' },
      { id: 'c7', name: 'Értékelési rubrika', task: 'Készítsen képet egy strukturált értékelési rubrikáról a(z) [TOPIC] témakörű projektek osztályozásához.', style: 'Structured Grading Table', composition: 'Checklist matrix with criteria nodes', elements: 'Performance levels, specific criteria, visual symbols', palette: 'Neutral with status colors', lighting: 'Flat office clarity', goal: 'Objektív értékelés.' },
      { id: 'c8', name: 'Mítosz–vadász poszter', task: 'Készítsen képet egy "Mítosz–vadász" poszterről: hibák és igazságok bemutatása a(z) [TOPIC] kapcsán.', style: 'Propaganda/Alert Poster Style', composition: 'Striking duo-tone split', elements: 'Large "X" and "Check" symbols, bold fonts', palette: 'Stark Red and Green', lighting: 'Harsh high-contrast lighting', goal: 'Tévhit–mentesítés.' },
      { id: 'c9', name: 'Sketch–note útmutató', task: 'Készítsen képet egy "Sketch–note" utasításkészletről a(z) [TOPIC] lényegének lerajzolásához.', style: 'Hand-Drawn Instructional Style', composition: 'Doodle-style step guide', elements: 'Simplified sketches, arrow connectors, bubble text', palette: 'Marker and paper aesthetic', lighting: 'Soft desk lamp glow', goal: 'Vizuális jegyzetelés.' },
      { id: 'c10', name: 'Mester Összefoglaló Táblázat', task: 'Készítsen képet egy Mester Összefoglaló Táblázatról a(z) [TOPIC] rendszerezéséhez.', style: 'Executive Knowledge Matrix', composition: 'High-level structured spreadsheet', elements: 'Summary icons, evidence links, action steps', palette: 'Deep professional corporate tones', lighting: 'High-key studio clarity', goal: 'Komplex szintézis.' }
    ]
  }
};

export const AGE_GROUPS = [
  { id: '10-14', label: '10–14 év (Alapfok)' },
  { id: '14-18', label: '14–18 év (Középfok)' },
  { id: '18+', label: '18+ év (Felsőfok)' }
];

export const LANGUAGES = [
  { id: 'hu', label: 'Magyar', flag: 'HU' },
  { id: 'en', label: 'Angol', flag: 'EN' },
  { id: 'zh', label: 'Mandarin', flag: 'CN' }
];
